kind: pipeline
type: docker
name: build

steps:
    - name: build
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          tags:
              - ${DRONE_BRANCH}
          dockerfile: ./.docker/php-fpm/Dockerfile
          repo: private.registry/repository
          registry: private.registry
      when:
          event:
              exclude:
                  - tag
