version: '3.4'

services:
    drone:
        image: 'drone/drone'
        environment:
            DRONE_AGENTS_ENABLED: 'true'
            DRONE_BITBUCKET_CLIENT_ID: ''
            DRONE_BITBUCKET_CLIENT_SECRET: ''
            DRONE_RPC_SECRET: ''
            DRONE_SERVER_PROTO: 'https'
            DRONE_SERVER_HOST: ''
            DRONE_TLS_AUTOCERT: 'true'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/lib/drone:/data'
        ports:
            - '443:443'
        restart: 'always'

    runner:
        image: 'drone/drone-runner-docker'
        environment:
            DRONE_RUNNER_NAME: 'runner'
            DRONE_RUNNER_CAPACITY: 4
            DRONE_RPC_PROTO: 'https'
            DRONE_RPC_HOST: ''
            DRONE_RPC_SECRET: ''
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        ports:
            - '3000:3000'
        restart: 'always'
        depends_on:
            - 'drone'
